version: '3'
services:
  timetogetawatch:
    build: ./TimeToGetAWatch
    ports:
      - "80:80"
  itstestingtime:
    build: ./ItsTestingTime
    ports:
      - "81:81"
    environment:
    - URI=http://timetogetawatch:80/api/time
    depends_on:
      - "timetogetawatch"